schema = 3

[mod]
  [mod."github.com/blues/jsonata-go"]
    version = "v1.5.4"
    hash = "sha256-pnSMib2jfSsbvykTdm7oyu05SQNE0A1CyolpNRGVduI="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/fatih/color"]
    version = "v1.16.0"
    hash = "sha256-Aq/SM28aPJVzvapllQ64R/DM4aZ5CHPewcm/AUJPyJQ="
  [mod."github.com/google/go-jsonnet"]
    version = "v0.20.0"
    hash = "sha256-c87I8MfPmcxoIy9IBFpybINh0UjcBaoReXfw/rJtqSI="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/santhosh-tekuri/jsonschema/v5"]
    version = "v5.3.1"
    hash = "sha256-G3shtLAutSrPjni+C9LAWDIeYfkr4R5pdKUVfAkB518="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stretchr/testify"]
    version = "v1.10.0"
    hash = "sha256-fJ4gnPr0vnrOhjQYQwJ3ARDKPsOtA7d4olQmQWR+wpI="
  [mod."golang.org/x/sys"]
    version = "v0.14.0"
    hash = "sha256-ReIRQmONicRW9idzGVPCBx5TTcKacmQTF1vPC3L4SxY="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.2.7"
    hash = "sha256-8qsfcWfn3D5HcOM37KG7yqHLWZrsTB1J6azy0SZnvUw="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.1.0"
    hash = "sha256-awYwA5r3OlWQbtBEIIY12g9nX73hBe3tmV7Lkpvc8Nw="
